### ISSUE TITLE
Ontwerpen 17-5

### ISSUE THREAD

**Issue by zenitba** [zenitba/connecting-people-realtime-web-app#1]
schetsen en Figma wireflow maken

**Comment by r20222** [comment]
Hier wil ik mee oefenen

**Comment by r20222** [comment]
Ik ga een figma ontwerp maken van de homepage, met de ingeklapte en uitgeklapte chatbox

**Comment by r20222** [comment]
Ik ga proberen de realtime animatie te maken met figma van de pinda als er een bericht binnenkomt
