### ISSUE TITLE
Wil je hier een <div> of een <fieldset>?

### ISSUE THREAD

**Issue by suustenvoorde** [zenitba/connecting-people-realtime-web-app#18]
Wat is de functie van deze div?

"<div> tags are very generic layout elements while <fieldset> is a layout element specifically for a set of form fields."

https://github.com/zenitba/connecting-people-realtime-web-app/blob/17b94ccb5c3d66668b320997742581091da809c8/views/index.ejs#L24

**Comment by zenitba** [comment]
betere class name gegeven
